package com.rick.management.car.spring.persit.domain;

// Generated Mar 16, 2014 1:24:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatXe generated by hbm2java
 */
@Entity
@Table(name = "dat_xe", catalog = "managementrendercar")
public class DatXe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer datXeId;
	private User user;
	private Date ngayDatThue;
	private String lienHe;
	private Set<ChiTietDatXe> chiTietDatXes = new HashSet<ChiTietDatXe>(0);

	public DatXe() {
	}

	public DatXe(User user) {
		this.user = user;
	}

	public DatXe(User user, Date ngayDatThue, String lienHe,
			Set<ChiTietDatXe> chiTietDatXes) {
		this.user = user;
		this.ngayDatThue = ngayDatThue;
		this.lienHe = lienHe;
		this.chiTietDatXes = chiTietDatXes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dat_xe_id", unique = true, nullable = false)
	public Integer getDatXeId() {
		return this.datXeId;
	}

	public void setDatXeId(Integer datXeId) {
		this.datXeId = datXeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quanly_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_dat_thue", length = 19)
	public Date getNgayDatThue() {
		return this.ngayDatThue;
	}

	public void setNgayDatThue(Date ngayDatThue) {
		this.ngayDatThue = ngayDatThue;
	}

	@Column(name = "lien_he", length = 100)
	public String getLienHe() {
		return this.lienHe;
	}

	public void setLienHe(String lienHe) {
		this.lienHe = lienHe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datXe")
	public Set<ChiTietDatXe> getChiTietDatXes() {
		return this.chiTietDatXes;
	}

	public void setChiTietDatXes(Set<ChiTietDatXe> chiTietDatXes) {
		this.chiTietDatXes = chiTietDatXes;
	}

}
