package com.rick.management.car.spring.persit.domain;

// Generated Mar 16, 2014 1:24:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DmXe generated by hbm2java
 */
@Entity
@Table(name = "dm_xe", catalog = "managementrendercar")
public class DmXe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer dmXeId;
	private GiaXe giaXe;
	private HangXe hangXe;
	private LoaiXe loaiXe;
	private String tenXe;
	private Integer soLuong;
	private String hinhAnh;
	private String thongTin;
	private Set<ChiTietDatXe> chiTietDatXes = new HashSet<ChiTietDatXe>(0);
	private Set<ChiTietNhapXe> chiTietNhapXes = new HashSet<ChiTietNhapXe>(0);

	public DmXe() {
	}

	public DmXe(HangXe hangXe, String tenXe) {
		this.hangXe = hangXe;
		this.tenXe = tenXe;
	}

	public DmXe(GiaXe giaXe, HangXe hangXe, LoaiXe loaiXe, String tenXe,
			Integer soLuong, String hinhAnh, String thongTin,
			Set<ChiTietDatXe> chiTietDatXes, Set<ChiTietNhapXe> chiTietNhapXes) {
		this.giaXe = giaXe;
		this.hangXe = hangXe;
		this.loaiXe = loaiXe;
		this.tenXe = tenXe;
		this.soLuong = soLuong;
		this.hinhAnh = hinhAnh;
		this.thongTin = thongTin;
		this.chiTietDatXes = chiTietDatXes;
		this.chiTietNhapXes = chiTietNhapXes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dm_xe_id", unique = true, nullable = false)
	public Integer getDmXeId() {
		return this.dmXeId;
	}

	public void setDmXeId(Integer dmXeId) {
		this.dmXeId = dmXeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gia_xe_id")
	public GiaXe getGiaXe() {
		return this.giaXe;
	}

	public void setGiaXe(GiaXe giaXe) {
		this.giaXe = giaXe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hang_xe_id", nullable = false)
	public HangXe getHangXe() {
		return this.hangXe;
	}

	public void setHangXe(HangXe hangXe) {
		this.hangXe = hangXe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loai_xe_id")
	public LoaiXe getLoaiXe() {
		return this.loaiXe;
	}

	public void setLoaiXe(LoaiXe loaiXe) {
		this.loaiXe = loaiXe;
	}

	@Column(name = "ten_xe", nullable = false, length = 50)
	public String getTenXe() {
		return this.tenXe;
	}

	public void setTenXe(String tenXe) {
		this.tenXe = tenXe;
	}

	@Column(name = "so_luong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "hinh_anh", length = 100)
	public String getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	@Column(name = "thong_tin")
	public String getThongTin() {
		return this.thongTin;
	}

	public void setThongTin(String thongTin) {
		this.thongTin = thongTin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dmXe")
	public Set<ChiTietDatXe> getChiTietDatXes() {
		return this.chiTietDatXes;
	}

	public void setChiTietDatXes(Set<ChiTietDatXe> chiTietDatXes) {
		this.chiTietDatXes = chiTietDatXes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dmXe")
	public Set<ChiTietNhapXe> getChiTietNhapXes() {
		return this.chiTietNhapXes;
	}

	public void setChiTietNhapXes(Set<ChiTietNhapXe> chiTietNhapXes) {
		this.chiTietNhapXes = chiTietNhapXes;
	}

}
