package com.rick.management.car.spring.persit.domain;

// Generated Mar 16, 2014 1:24:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HangXe generated by hbm2java
 */
@Entity
@Table(name = "hang_xe", catalog = "managementrendercar")
public class HangXe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer hangXeId;
	private String tenHangXe;
	private Set<DmXe> dmXes = new HashSet<DmXe>(0);

	public HangXe() {
	}

	public HangXe(String tenHangXe) {
		this.tenHangXe = tenHangXe;
	}

	public HangXe(String tenHangXe, Set<DmXe> dmXes) {
		this.tenHangXe = tenHangXe;
		this.dmXes = dmXes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hang_xe_id", unique = true, nullable = false)
	public Integer getHangXeId() {
		return this.hangXeId;
	}

	public void setHangXeId(Integer hangXeId) {
		this.hangXeId = hangXeId;
	}

	@Column(name = "ten_hang_xe", nullable = false, length = 50)
	public String getTenHangXe() {
		return this.tenHangXe;
	}

	public void setTenHangXe(String tenHangXe) {
		this.tenHangXe = tenHangXe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hangXe")
	public Set<DmXe> getDmXes() {
		return this.dmXes;
	}

	public void setDmXes(Set<DmXe> dmXes) {
		this.dmXes = dmXes;
	}

}
