package com.rick.management.car.spring.persit.domain;

// Generated Mar 16, 2014 1:24:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiXe generated by hbm2java
 */
@Entity
@Table(name = "loai_xe", catalog = "managementrendercar")
public class LoaiXe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer loaiXeId;
	private String tenLoaiXe;
	private Set<DmXe> dmXes = new HashSet<DmXe>(0);

	public LoaiXe() {
	}

	public LoaiXe(String tenLoaiXe) {
		this.tenLoaiXe = tenLoaiXe;
	}

	public LoaiXe(String tenLoaiXe, Set<DmXe> dmXes) {
		this.tenLoaiXe = tenLoaiXe;
		this.dmXes = dmXes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "loai_xe_id", unique = true, nullable = false)
	public Integer getLoaiXeId() {
		return this.loaiXeId;
	}

	public void setLoaiXeId(Integer loaiXeId) {
		this.loaiXeId = loaiXeId;
	}

	@Column(name = "ten_loai_xe", nullable = false, length = 50)
	public String getTenLoaiXe() {
		return this.tenLoaiXe;
	}

	public void setTenLoaiXe(String tenLoaiXe) {
		this.tenLoaiXe = tenLoaiXe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiXe")
	public Set<DmXe> getDmXes() {
		return this.dmXes;
	}

	public void setDmXes(Set<DmXe> dmXes) {
		this.dmXes = dmXes;
	}

}
