package com.rick.management.car.spring.persit.domain;

// Generated Mar 16, 2014 1:24:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhapXe generated by hbm2java
 */
@Entity
@Table(name = "nhap_xe", catalog = "managementrendercar")
public class NhapXe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nhapXeId;
	private User user;
	private Date ngayNhap;
	private Set<ChiTietNhapXe> chiTietNhapXes = new HashSet<ChiTietNhapXe>(0);

	public NhapXe() {
	}

	public NhapXe(User user, Date ngayNhap, Set<ChiTietNhapXe> chiTietNhapXes) {
		this.user = user;
		this.ngayNhap = ngayNhap;
		this.chiTietNhapXes = chiTietNhapXes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nhap_xe_id", unique = true, nullable = false)
	public Integer getNhapXeId() {
		return this.nhapXeId;
	}

	public void setNhapXeId(Integer nhapXeId) {
		this.nhapXeId = nhapXeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quanli_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_nhap", length = 19)
	public Date getNgayNhap() {
		return this.ngayNhap;
	}

	public void setNgayNhap(Date ngayNhap) {
		this.ngayNhap = ngayNhap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapXe")
	public Set<ChiTietNhapXe> getChiTietNhapXes() {
		return this.chiTietNhapXes;
	}

	public void setChiTietNhapXes(Set<ChiTietNhapXe> chiTietNhapXes) {
		this.chiTietNhapXes = chiTietNhapXes;
	}

}
