package com.rick.management.car.spring.persit.domain;

// Generated Mar 16, 2014 1:24:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quyen generated by hbm2java
 */
@Entity
@Table(name = "quyen", catalog = "managementrendercar")
public class Quyen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer quyenId;
	private String quyenName;
	private Set<DmQuyen> dmQuyens = new HashSet<DmQuyen>(0);

	public Quyen() {
	}

	public Quyen(String quyenName) {
		this.quyenName = quyenName;
	}

	public Quyen(String quyenName, Set<DmQuyen> dmQuyens) {
		this.quyenName = quyenName;
		this.dmQuyens = dmQuyens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "quyen_id", unique = true, nullable = false)
	public Integer getQuyenId() {
		return this.quyenId;
	}

	public void setQuyenId(Integer quyenId) {
		this.quyenId = quyenId;
	}

	@Column(name = "quyen_name", nullable = false, length = 30)
	public String getQuyenName() {
		return this.quyenName;
	}

	public void setQuyenName(String quyenName) {
		this.quyenName = quyenName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quyen")
	public Set<DmQuyen> getDmQuyens() {
		return this.dmQuyens;
	}

	public void setDmQuyens(Set<DmQuyen> dmQuyens) {
		this.dmQuyens = dmQuyens;
	}

}
